spring:
  application:
    name: usercenter
  # ?? dev ??
  profiles:
    active: dev
  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session ??
  session:
    # todo ????????? session????? Redis?
    # store-type: redis
    # 30 ???
    timeout: 2592000
  # ?????
  # todo ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zijin
    username: root
    password: 123456
server:
  port: 8123
